### ISSUE TITLE
iTaigi 愛台語

### ISSUE THREAD

**Issue by wdv4758h** [zdict/zdict#115]
https://itaigi.tw/

From: #108

**Comment by M157q** [comment]
- [x] basic mode
- [x] verbose mode
- [ ] tests
- [ ] documentation

**Comment by M157q** [comment]
![20190330_21:15:28](https://user-images.githubusercontent.com/1645228/55276638-07bf6f00-5331-11e9-990c-648595295e29.jpg)
![20190330_21:15:45](https://user-images.githubusercontent.com/1645228/55276640-0a21c900-5331-11e9-957f-af81259c8680.jpg)
