### ISSUE TITLE
Interactive mode hangs when users change to the nework different from the one they were using when started zdict

### ISSUE THREAD

**Issue by M157q** [zdict/zdict#134]
For example, I opened zdict interactive mode when I was using Wi-Fi with SSID `foo`. Then, I disconnect `foo` and connect to Wi-Fi with SSID `bar`. Now, if I try to use  zdict with interactive mode to search some word, it just hangs.

**Comment by iblis17** [comment]
IIRC, we have timeout exception for query.

**Comment by M157q** [comment]
@iblis17 Yes, the default timeout is 5 seconds. But, this bug somehow will not raise the TimeoutError even if it hangs more than 5 seconds. I should find some time to record a video to show how this bug looks like.

**Comment by M157q** [comment]
Hmm... this bug cannot be reproduced after I uses v0.10.0.

**Comment by wdv4758h** [comment]
lol

**Comment by iblis17** [comment]
~labled~

**Comment by M157q** [comment]
We need `git bisect`
