### ISSUE TITLE
Wiktionary support

### ISSUE THREAD

**Issue by iblis17** [zdict/zdict#196]
- https://en.wiktionary.org/wiki/Wiktionary:Main_Page
- https://zh.wiktionary.org/zh-hant/Wiktionary:%E9%A6%96%E9%A1%B5

**Comment by AlexandruValeanu** [comment]
Is this still relevant? If so, I'd like to work on it.

**Comment by iblis17** [comment]
yeah. Any contributions are welcomed.

**Comment by wdv4758h** [comment]
go ahead :+1:
