### ISSUE TITLE
Add no VT100 color print option

### ISSUE THREAD

**Issue by M157q** [zdict/zdict#23]
![screen shot 2015-07-14 at 4 16 50 pm](https://cloud.githubusercontent.com/assets/1645228/8669071/de45484e-2a43-11e5-9ae5-9242cfbffd95.png)

For the output redirection, should get rid of those VT100 color codes.

**Comment by pi314** [comment]
```
# Detect if stdout is a terminal
if sys.stdout.isatty():
    # output to a real terminal
    ...
else:
    # output being piped or redirected
    ...
```

**Comment by iblis17** [comment]
Merged

**Comment by pi314** [comment]
NOooo, we need a `--color` option to force color printing, or `zdict.vim` gets not color

**Comment by pi314** [comment]
maybe use `-c` and `--force-color` as option name
