### ISSUE TITLE
More complete testing

### ISSUE THREAD

**Issue by iblis17** [zdict/zdict#3]
1. https://docs.python.org/3.4/library/unittest.html
2. https://pypi.python.org/pypi/coverage/3.7.1
3. https://travis-ci.org/
4. https://tox.readthedocs.org/en/latest/
5. [nose](https://nose.readthedocs.org/en/latest/)

**Comment by M157q** [comment]
ref #39, #40, #41, #42, #43

**Comment by M157q** [comment]
@iblis17 I'm gonna close this issue. Just add new issues like u did recently for the fure testing.
