### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-d6jh0yc4/zdict/

### ISSUE THREAD

**Issue by cloudayc** [zdict/zdict#331]
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-d6jh0yc4/zdict/

command:
pip install zdict
and same issue command:
python3 -m pip install zdict

**Comment by M157q** [comment]
@cloudayc Can you show me what's your Python3 version and paste the entire traceback log?

**Comment by cloudayc** [comment]
> @cloudayc Can you show me what's your Python3 version and paste the entire traceback log?
➜  ~ python3 --version
Python 3.6.5

trace log:
Collecting zdict
  Using cached https://files.pythonhosted.org/packages/79/ee/0587bb15cd9ba3f2b3c8d299c995a6c142a1367fd210d033b9f861520d25/zdict-2.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/pip/_internal/download.py", line 444, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/2s/v251zhtj2z11m0mm_fjykkdw0000gp/T/pip-install-6epy4zc3/zdict/requirements-test.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2s/v251zhtj2z11m0mm_fjykkdw0000gp/T/pip-install-6epy4zc3/zdict/setup.py", line 76, in <module>
        tests_require=get_test_req(),
      File "/private/var/folders/2s/v251zhtj2z11m0mm_fjykkdw0000gp/T/pip-install-6epy4zc3/zdict/setup.py", line 33, in get_test_req
        test_requires = [str(tr.req) for tr in test_requirements]
      File "/private/var/folders/2s/v251zhtj2z11m0mm_fjykkdw0000gp/T/pip-install-6epy4zc3/zdict/setup.py", line 33, in <listcomp>
        test_requires = [str(tr.req) for tr in test_requirements]
      File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_file.py", line 103, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/usr/local/lib/python3.6/site-packages/pip/_internal/download.py", line 448, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip._internal.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: '/private/var/folders/2s/v251zhtj2z11m0mm_fjykkdw0000gp/T/pip-install-6epy4zc3/zdict/requirements-test.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2s/v251zhtj2z11m0mm_fjykkdw0000gp/T/pip-install-6epy4zc3/zdict/

**Comment by M157q** [comment]
@cloudayc Could you try if this error fixed in zdict-2.0.3?

**Comment by cloudayc** [comment]
> @cloudayc Could you try if this error fixed in zdict-2.0.3?

It works! thanks!

but I got a new issue after installation:

➜  ~ zdict
Didn't detect your LC_ALL environment variable.
Please export LC_ALL with some UTF-8 encoding.
➜  ~ zdict hello
Didn't detect your LC_ALL environment variable.
Please export LC_ALL with some UTF-8 encoding.

how to set this?

**Comment by M157q** [comment]
@cloudayc try `export LC_ALL=en_US.UTF-8`

**Comment by cloudayc** [comment]
> @cloudayc Try `export LC_ALL=en_US.UTF-8`

Problem sovled.thanks!
