### ISSUE TITLE
Is Urban Dictionary API free to use?

### ISSUE THREAD

**Issue by MHShetty** [zdict/zdict#369]
Can Urban Dictionary API be used for free (for commercial use) assuming that I won't be charging the users to use the API?

If it is free, then is there any request limit? What if there are too many requests which the server cannot handle? Do I need someone else's consent before using this API for my app?

Lastly, where can I obtain a license for using this API to ensure that they are no issues in the future..?

**Comment by BerdyGaming** [comment]
I think for commercial, non earning use it might be free but I am not entirely sure.

**Comment by MHShetty** [comment]
Whom can I contact in order to know the exact limitations of this API?
Is there any page where I can obtain a license for the same?

**Comment by BerdyGaming** [comment]
I guess the person behind the repo will answer. You could probably contact him in PMs or some contacts

**Comment by MHShetty** [comment]
> I guess the person behind the repo will answer. You could probably contact him in PMs or some contacts
I tried searching Urban Dictionary's official website but it's T&C were a bit tricky and there was no direct mention about the API.

Actually I am new to GitHub as an registered user so could you please explain how could I exactly contact the person behind this repo or is there any way I can make a direct reference to him via the thread we are currently on?

**Comment by BerdyGaming** [comment]
I don't think thw has urban have an officially stated API on their site, I think I read in an issue here that it's not official. About the licencing, someone higher up would probably contact you or write under this issue

**Comment by MHShetty** [comment]
> I don't think thw has urban have an officially stated API on their site, I think I read in an issue here that it's not official. About the licencing, someone higher up would probably contact you or write under this issue

Is there any way I can bring this issue/query to his notice?

**Comment by BerdyGaming** [comment]
It's created so he should notice it really. Nothing much you can do

**Comment by M157q** [comment]
Can't answer this for you.
Check: <https://about.urbandictionary.com/tos>

**Comment by MHShetty** [comment]
> > I guess the person behind the repo will answer. You could probably contact him in PMs or some contacts
> 
> I tried searching Urban Dictionary's official website but it's T&C and Privacy Policy had no direct mention about the API.
> 
> Actually I am new to GitHub as an registered user and this is my first thread so could you please explain how exactly could I contact the person behind this repo or is there any way I can make a direct reference to him via the thread we are currently on?
> 
> Terms of Service of Urban Dictionary:
> https://about.urbandictionary.com/tos
> 
> > Access to the Urban Dictionary API is available only with the express permission of Urban Dictionary and is governed by the Urban Dictionary API Terms of Service.
> 
> So I need to contact Urban Dictionary to use their API...(Please correct me if I am wrong)
> But I didn't get the second part of the sentence, They have made no mention about their API in the rest of the page so what are they exactly referring to?
