### ISSUE TITLE
could not use oxford dictionary

### ISSUE THREAD

**Issue by stanosaka** [zdict/zdict#385]
zdict -dt oxford cool 
Oxford: No entry is found.
"cool" not found!

**Comment by iblis17** [comment]
cc @tzing

**Comment by M157q** [comment]
Oxford dictionary changed its API to
`https://od-api.oxforddictionaries.com:443/api/v2/entries/{language}/{word}
![20200529_23:37:20](https://user-images.githubusercontent.com/1645228/83277949-61f1e380-a205-11ea-98d6-f838b644e3a8.jpg)
`

**Comment by M157q** [comment]
@stanosaka This bug should be fixed in the zdict 3.5.0. Try it and tell us if it works.

**Comment by stanosaka** [comment]
Thanks @M157q , it's working now
