### ISSUE TITLE
How to run in Jupiter notebook?

### ISSUE THREAD

**Issue by chenmingxue** [zdict/zdict#412]
Can you give some example?

**Comment by iblis17** [comment]
cc @wdv4758h

**Comment by wdv4758h** [comment]
There is another repo called [zdict_jupyter](https://github.com/zdict/zdict_jupyter).
After installing both zdict and zdict_jupyter, you can choose the zdict kernel at Jupyter notebook.

![jupyter1](https://user-images.githubusercontent.com/2716047/81496174-32eeee80-92a5-11ea-9a3b-f8729f496e50.png)
![jupyter2](https://user-images.githubusercontent.com/2716047/81496176-35e9df00-92a5-11ea-9229-e8850a05fd04.png)


The zdict_jupyter repo does not have update for a while, but it's still working. However, it doesn't support choosing other dictionary right now.
