### ISSUE TITLE
Auto discover `XDict` in dir dictionaries

### ISSUE THREAD

**Issue by iblis17** [zdict/zdict#44]
Let user not to register `XDict` in `dictionaries.__init__.py` manually.

**Comment by M157q** [comment]
Do you have any idea about how to do it?

**Comment by iblis17** [comment]
Simple idea: Leverage `importlib`, `dir` ... etc

**Comment by iblis17** [comment]
Hope this useful https://docs.python.org/3/reference/import.html#finders-and-loaders

**Comment by iblis17** [comment]
@M157q please review the code first

I will add test cases for it later

**Comment by iblis17** [comment]
Merged

**Comment by M157q** [comment]
:+1:
