### ISSUE TITLE
zdict only works with UTF-8

### ISSUE THREAD

**Issue by corgile** [zdict/zdict#453]
Desktop> zdict
zdict only works with encoding=UTF-8,
but your encoding is: en_US cp936
Please export LC_ALL with some UTF-8 encoding.
For example: `export LC_ALL=en_US.UTF-8`
![image](https://user-images.githubusercontent.com/48396880/89162013-04339c00-d5a6-11ea-9735-2506d6374418.png)

平台：windows+gitbash（mintty）

**Comment by M157q** [comment]
Did you try the command `export LC_ALL=en_US.UTF-8`?
It looks like the answer is NO.

I think you can try the command `export LC_ALL=zh_CN.UTF-8`.

**Comment by corgile** [comment]
I tried, and also edited /etc/profile by adding line `export LC_ALL=en_US.UTF-8` and `export LC_ALL="en_US.UTF-8"` but it still didn't work

**Comment by mlouielu** [comment]
Could you test with:

```
$ export LC_ALL=zh_CN.UTF-8
$ zdict
```

**Comment by corgile** [comment]
> Could you test with:

## well, please check this out.  

### As you can tell from this GIF, i tried every possible way but still the same

![x~2](https://user-images.githubusercontent.com/48396880/89177363-d9edd880-d5bd-11ea-8937-0f4cd0b425fb.gif)

**Comment by M157q** [comment]
@corgile Could you try the solution 1 in this blog post?
<https://blog.csdn.net/u013068377/article/details/52168434>

**Comment by corgile** [comment]
Alright, I think I better give it up&nbsp;
