### ISSUE TITLE
APC e-dictionary need fixed, endpoint moved.

### ISSUE THREAD

**Issue by mlouielu** [zdict/zdict#491]
They move the website from https://e-dictionary.apc.gov.tw to https://e-dictionary.ilrdf.org.tw.

But seems the API changed a lot, I have no way to simply fix it :cry:

**Comment by M157q** [comment]
It's fine.
Maybe we have to remove it at this time.
And add it back once we fixed it.

**Comment by M157q** [comment]
ref: #448

**Comment by M157q** [comment]
Will remove APC in zdict 5.0.0
