### ISSUE TITLE
The `readline` module on Mac OS X has strange behavior

### ISSUE THREAD

**Issue by pi314** [zdict/zdict#50]
* Mac OS X 10.10 with Python3.4
  * `import readline` causes some escape sequence being output to terminal, although that is not visible
* Mac OS X 10.10 with Python3.5
  * Ctrl-D not working correctly.
  *  After enter-and-leave zdict shell (or any `readline` based shell, even Python shell), my zsh cannot be exited with Ctrl-D, but if I run `zdict -h`, problem disappeared.

`gnureadline` module works fine.

I want to check the platform, if `sys.platform` == 'darwin', install `gnureadline` instead.

**Comment by pi314** [comment]
Ok I found the problem.
On my Mac OS X, Python3.5, installed from Mac Ports, Python interactive shell automatically imports `readline` module, which is `/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload/readline.cpython-35m-darwin.so`, but that file is possibly broken.
There is another readline `.so` file in `/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages`, which is good.
So I work around it with soft link, and problem solved :|

**Comment by pi314** [comment]
Anyway, I just commit it :|

**Comment by M157q** [comment]
So, do we really need this commit or it's just the problem on your MacBook?

**Comment by M157q** [comment]
Hmm...
ok. It seems this commit won't influence non-Mac users and can solve the problem which you encountered for those Mac users who might encounter this potentially.

Maybe we need a unit-test for this issue? or we just close it?

**Comment by pi314** [comment]
I can try to write an unit test for it.
Btw, I accidentally push it on to master branch, what should I do now XDDD?
`git push --force` or `git revert`? And move it to another branch

**Comment by M157q** [comment]
`$ git revert HEAD` then push
