### ISSUE TITLE
SpanishDict dictionary support

### ISSUE THREAD

**Issue by wdv4758h** [zdict/zdict#58]
|  | Status |
| ---- | ---- |
| Official JSON API | No |
| Support Languages | English <-> Spanish |
| Possible Implementation | Parsing HTML |
| URL | `http://www.spanishdict.com/translate/{word}` |

![spanish-dict](https://cloud.githubusercontent.com/assets/2716047/11324516/18de293e-916f-11e5-8cf1-b36f6fa19a02.png)

**Comment by iblis17** [comment]
:+1: 
How about update `README`?

**Comment by wdv4758h** [comment]
@iblis17 I was writing it :P https://github.com/zdict/zdict/commit/9b57902341e215aecf9a8e328c175c9705cf8746

**Comment by iblis17** [comment]
:+1:

**Comment by M157q** [comment]
:+1:
