### ISSUE TITLE
Does zdict has to query every arguments, or concat them into one phrase？

### ISSUE THREAD

**Issue by pi314** [zdict/zdict#61]
Have you ever use zdict to query multiple words in one time?
If not, I suggest concatenating every word with a space character:

```
$ zdict as soon as possible
```

**Comment by wdv4758h** [comment]
@pi314 is this what you want ?

```sh
$ zdict "and so on"
```

**Comment by pi314** [comment]
@wdv4758h ：Yes, but I want to remove these `"`, because I never query multiple words in one time.

**Comment by iblis17** [comment]
I do not want to confuse user agaist unix cmd convention:  
"if you means one argument, explictly quote them;  we use white space to tell cmd that there are lots of args."

**Comment by iblis17** [comment]
If we think the feature, query multiple words, is redundent,  just remove it:
user place multiple args on cmd, then raise exception.

**Comment by iblis17** [comment]
Or we have another option:
Let this behavior configurable in the future, but disabled by default.

*The hidden feature*

**Comment by pi314** [comment]
@iblis17 : I agree with your opinion: "argument with spaces should be quoted" :3
And I agree that behavior should not be default XD.

**Comment by M157q** [comment]
I think we can use a `zdictrc` for this issue.
